spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/academicabi
spring.datasource.username=postgres
spring.datasource.password=Dangerzone_2205
spring.datasource.driver-class-name=org.postgresql.Driver
